export function getLogos() {

return [
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png"
    },
    {
        url:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png"
    },
]
}
